//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TattooShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cita()
        {
            this.Trabajo = new HashSet<Trabajo>();
        }
    
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public double deposito { get; set; }

        [Display(Name = "Cliente")]
        public Nullable<int> cliente_id { get; set; }

        [Display(Name = "Tipo de Trabajo")]
        public Nullable<int> tipo_trabajo_id { get; set; }

        [Display(Name = "Artista")]
        public Nullable<int> artista_id { get; set; }
    
        public virtual Artista Artista { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual TipoTrabajo TipoTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trabajo> Trabajo { get; set; }
    }
}
